//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bon_liv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bon_liv()
        {
            this.commandes = new HashSet<commandes>();
        }
    
        public int num_BonLiv { get; set; }
        public Nullable<decimal> montant_total { get; set; }
        public System.DateTime date_ajout { get; set; }
        public byte status { get; set; }
        public Nullable<System.DateTime> date_liv { get; set; }
        public Nullable<int> num_piece { get; set; }
        public Nullable<System.DateTime> date_Payement { get; set; }
        public byte payment_mode { get; set; }
        public Nullable<int> bon_enlev { get; set; }
    
        public virtual bon_enlev bon_enlev1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commandes> commandes { get; set; }
    }
}
