//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bon_enlev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bon_enlev()
        {
            this.la_charge = new HashSet<la_charge>();
            this.bon_liv = new HashSet<bon_liv>();
        }
    
        public int id { get; set; }
        public int chaufeur { get; set; }
        public int citerne { get; set; }
        public int tracteur { get; set; }
        public byte mode { get; set; }
        public System.DateTime programme { get; set; }
        public byte status { get; set; }
        public int etable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<la_charge> la_charge { get; set; }
        public virtual vehicule vehicule { get; set; }
        public virtual chaufeur chaufeur1 { get; set; }
        public virtual vehicule vehicule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_liv> bon_liv { get; set; }
    }
}
