//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class chaufeur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chaufeur()
        {
            this.disponible = 1;
            this.bon_enlev = new HashSet<bon_enlev>();
        }
    
        public int chauf_num { get; set; }
        public Nullable<int> transporteur { get; set; }
        public int person { get; set; }
        public string permis { get; set; }
        public System.DateTime permis_debut { get; set; }
        public byte disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_enlev> bon_enlev { get; set; }
        public virtual person person1 { get; set; }
        public virtual transporteur transporteur1 { get; set; }
    }
}
