//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class commandes
    {
        public int id { get; set; }
        public int client { get; set; }
        public int produit { get; set; }
        public int bon_liv { get; set; }
        public int prod_qnt { get; set; }
        public Nullable<int> emb { get; set; }
        public Nullable<decimal> montant_ligne { get; set; }
    
        public virtual client client1 { get; set; }
        public virtual produit produit1 { get; set; }
        public virtual bon_liv bon_liv1 { get; set; }
    }
}
