//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class la_charge
    {
        public byte cmp { get; set; }
        public int rotation { get; set; }
        public int produit { get; set; }
        public int qnt { get; set; }
        public Nullable<int> emb { get; set; }
    
        public virtual bon_enlev bon_enlev { get; set; }
        public virtual produit produit1 { get; set; }
    }
}
