//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class naftall1Entities1 : DbContext
    {

        public naftall1Entities1()
            : base("name=AppConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<commandes> commandes { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<produit> produit { get; set; }
        public virtual DbSet<transporteur> transporteur { get; set; }
        public virtual DbSet<bon_enlev> bon_enlev { get; set; }
        public virtual DbSet<la_charge> la_charge { get; set; }
        public virtual DbSet<vehicule> vehicule { get; set; }
        public virtual DbSet<chaufeur> chaufeur { get; set; }
        public virtual DbSet<bon_liv> bon_liv { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
