//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public int id { get; set; }
        public int person { get; set; }
        public string mot_pass { get; set; }
        public int role { get; set; }
        public string user_name { get; set; }
    
        public virtual person person1 { get; set; }
    }
}
