//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace naftaall1.Local_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicule()
        {
            this.disponible = 1;
            this.bon_enlev = new HashSet<bon_enlev>();
            this.bon_enlev1 = new HashSet<bon_enlev>();
        }
    
        public int veh_num { get; set; }
        public Nullable<int> transporteur { get; set; }
        public byte privee { get; set; }
        public byte disponible { get; set; }
        public string matricule { get; set; }
        public byte type_vih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_enlev> bon_enlev { get; set; }
        public virtual transporteur transporteur1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bon_enlev> bon_enlev1 { get; set; }
    }
}
